import Head from 'next/head'
import Link from 'next/link'
import SecondarySection from '../components/SecondarySection'
import styles from '../styles/About.module.css'



export default function About() {

  return (
    <>
      <Head>
        <title>Action 1 Qwik Service | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.about}>
        <h1>About Action 1 Qwik Service</h1>
        <div className={styles.horizRule}></div>
        <p>Action 1 Automotive has 2 locations: A downtown Rochester location and a Quick Service Center on the south end of Rochester Hills, MI. The Downtown Location is a state of the art Facility where customers can actually watch their cars being worked on with the windows in the waiting room looking down to a seven bay garage. Our policy is our Honesty and Integrity.</p>
        <div className={styles.group}>
          <SecondarySection
            title="Our Mission"
            text="Our safety depends on the mechanical condition of your vehicle. That’s why we make it our #1 priority to provide you exceptional service, ASE-certified technicians with many years of experience, the highest quality parts, and our own guarantee you’ll be satisfied with our work."
          />
          <SecondarySection
            title="Why Choose Us"
            text="Our shop employs honest ASE-certified technicians and mechanics, and we use the latest technology and equipment for our repairs. Because we are a certified Auto Center, we are able to provide the benefits of an established national company while offering the personal touch of a local business. We understand that your vehicle is a major investment, and that is why we care for each customer’s vehicle as if it were our own. Contact Us!"
          />
        </div>
        <Link href="/contact">
          <a className='btn btn-red m-0'>CONTACT US</a>
        </Link>
      </div>
    </>
  )
}
