import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/ServicesPage.module.css'
import TitleTextList from '../components/TitleTextList'
import SecondarySection from '../components/SecondarySection'

export default function services() {
  return (
    <div>
      <Head>
        <title>Action 1 Qwik Service | Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.services}>
        <h1>Action 1 Qwik Service</h1>
        <div className={styles.horizRule}></div>
        <p>As your local full-service auto repair shop, Action One Qwik Service takes care of your car from headlights to tail lights. We specialize in full auto diagnostic services using the latest computer technologies so you can get a fast, accurate diagnosis for your car. Our car diagnostic services help get you back on the road quickly and safely, finding the problem the first time and providing you with a responsible repair. The mechanics at Action One Qwik Service aren’t just ASE Certified – they practice exceptional customer service, providing you with all of the information you need to make a smart decision about your car repair.</p>
        <div className={styles.group}>
          <SecondarySection
            title="Scheduled Services"
            text="Schedule your car care services with us today; whether it is a simple oil change or a complete engine overhaul, we are your one stop service shop."
          />
          <SecondarySection
            title="Towing"
            text="Action 1 Qwik Service is conveniently located and can usually provide a very quick response to towing requests in any of the surrounding areas."
          />
          <SecondarySection
            title="Oil Changes"
            text="Action 1 Qwik Service is particularly specialized in providing quick services that get you back on the road fast. This means oil changes. Fast oil changes."
          />
          <SecondarySection
            title="Auto Repair"
            text="Just because the Action 1 Qwik Service location is streamlined to get you back on the road fast does not mean that we limit our services at this location."
          />
        </div>
        <div className={styles.group}>
          <TitleTextList
            title="From quick services like"
            text="Our mechanics can perform jobs at any of our facilities. This means we can provide you with any service or repair you may need if your repair needs increase."
            list={[
              'Oil Changes',
              'Brakes',
              'Tune Ups',
              'Computer Diagnostics',
              'Fluid Leaks',
              'Tire Rotation',
              'Batteries',
              'Belts & Hoses',
              'Towing'
            ]}
          />
          <TitleTextList
            title="To more advanced services like"
            text="Our mechanics are certified to perform an easy task like changing your oil, too the most advanced services like transmission repair."
            list={[
              "Engine Repair",
              "Suspension Repair",
              "Transmission Service and Repair",
              "Air Conditioning Recharge and Repair",
              "Electrical Systems Diagnostics",
              "Water Pump Replacement",
              "Heating & Cooling",
              "Tune Ups & Auto Maintenance",
              "Steering Repair"
            ]}
          />
        </div>
      </div>
    </div>
  )
}
